project_id = "qifuvbfyqntktzafzgac"

[functions.submit-candidatura]
verify_jwt = false

[functions.export-candidature]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.admin-data]
verify_jwt = false

[functions.gtm-config]
verify_jwt = false
